spring.application.name=ShareIt
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
spring.datasource.username=shareit_user
spring.datasource.password=shareit_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

logging.level.ru.practicum=DEBUG
logging.level.org.springframework.web=INFO