spring.application.name=ShareIt
server.port=8080

# ????????? ????????? ???, ??? ??????? ? ??
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

# ???????????
logging.level.ru.practicum=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.boot=INFO

# ????????? DataSource
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=