spring:
  application:
    name: ShareIt Server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shareit
    username: shareit_user
    password: shareit_pass

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 9090

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE